server:
  port: 8081
  tomcat:
    max-connections: 200    # ?? ?? ?? ?
    
# ????? ?? ??
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB    # ? ??? ?? ???(default 1MB)
      max-request-size: 200MB # ??? ??? ? ???(default 10NB)
  web:
    resources:
      static-locations: file:D:///2.BootCamp/1000_UploadFiles/ #?? ??? ??
      cache-period : 3600                                     # ? ????? ?? ??(?, 1??)

filepath: D:\2.BootCamp\1000_UploadFiles
